package com.peaas.fsm.enums;

public enum Events {
	ROUTING_SUCCESS, ROUTING_ERROR, PUSH_TO_AMIGO,SCREENING_SUSPENDED, SCREENING_DONE, DO_SCREENING, PUSH_TO_AMIGO_FAILED, RO_VERIFICATION_SUCCESS, RO_VERIFICATION_FAILED
}
