package com.peaas.fsm.enums;

public enum States {
	ISSUED, ROUTING_DONE, ROUTING_FAILED, END, SERVICE_PROVIDER_DONE,AML_SUSPENDED,BLACKLIST_SCANNING_COMPLETED, RO_VERIFICATION_DONE, RO_VERIFICATION_FAILED, AVAILABLE_FOR_MANUAL_RO
}
